### ISSUE TITLE
Construction of 2 Helical UHF v2

### ISSUE THREAD

**Issue by boctok01** [satnogs/satnogs-antennas#3]
Test designs of issue #2 by constructing a LHP and RHP helical UHF v2 antennas.

**Comment by ppapadeas** [comment]
Results from 10 turn v2 design.
![uploads/0b7506ea-e145-46b1-90d9-4578960b000c/uhf-helical-v2.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0b7506ea-e145-46b1-90d9-4578960b000c%2Fuhf-helical-v2.png)
